### PR TITLE
Create the basic scaffold of the new Kaching app

### LINKED ISSUE #2: Create the basic scaffold of the new Kaching app
Step 2 of this issue: https://github.com/UseKeyp/kaching-app/issues/1

### PR DESCRIPTION
**Pull request by alekseevaiana**
Closes #2 
- new navbar component
- new user account component

### CODE REVIEW

**Comment by jahabeebs** [comment]
I think pat is reviewing in the future but I took a look and the components are looking great 👍 some suggestions: 

- get rid of the bluish tint at the top of the user account component
- fix the user account component to the top but add padding that corresponds to the design (notice how it's in the same place at the top on each screen)
- and similarly is to fix the route icons at the bottom of the screen like how it corresponds to the design. 

the homepage background should be different than the login screen background but we can fix this in a later issue

**Review by jahabeebs — CHANGES_REQUESTED** [review]
@alekseevaiana Hi Iana the changes are good that you made to the user account component and icons with routes. However I noticed that the login page has disappeared once a user signs out

https://github.com/UseKeyp/kaching-app/assets/47253537/380733fb-e3a4-4c5d-8e3f-3e344ee28c4c

i have a feeling it's because of this logic you added: 
```
 {router.pathname !== "/login" && (
                <>
                  <UserAccount />
                  <Box paddingTop="150px">
                    <Component {...pageProps} />
                  </Box>
                  <Navbar />
                </>
              )}{" "}
```
_app.tsx is the entry point to our application so it's possible that now the login page never renders if we're on the login route

**Comment by alekseevaiana** [comment]
@jahabeebs thanks for noticing, I fixed, hope that works.

### Login page
Screenshot 2023-06-02 at 4 06 11 PM

### Start page after login:
Screenshot 2023-06-02 at 4 06 24 PM

### `/` page
I didn't do styling here, but in the future, I think we should find a way how to scroll only the content of the pages. Let me know if I should do it in this PR.
Screenshot 2023-06-02 at 4 06 01 PM

**Review by jahabeebs — APPROVED** [review]
nice

**Comment by jahabeebs** [comment]
also next time please press "re-request review" when you want me to review it again

**Pull request merged**
