### PR TITLE
Kaching Redesign [5]: Recipient toggle, confirm recipient

### LINKED ISSUE #8: Kaching Redesign [5]: Recipient toggle, confirm recipient
For now we should be able to toggle between Discord and Gmail. Note that the placeholder text should change when clicking between Gmail and Discord. The Twitter and Twitch icons can remain greyed out. 

- Create the confirm recipient button. After entering a username/email and pressing confirm recipient, it should bring the user back to the main page of /send and have their info auto-populated in the recipient field. Note that under the recipient field it says "sending to" and then the icon of the selected provider

after clicking the text input box for recipient (it will be blank originally)

Screenshot 2023-05-19 at 3 10 52 PM

we get brought to this where we can select a provider/enter a recipient (see figma: https://www.figma.com/proto/cAvSKcYAOcVjK7RZeCWjlx/Kaching?node-id=902-5460&starting-point-node-id=812%3A2119)

Screenshot 2023-06-02 at 6 47 34 PM

Acceptance criteria:
- confirm recipient page with discord and google icons that you can toggle through (don't worry about the other providers for now)
- after toggling between discord and gmail and entering a recipient and pressing confirm recipient you're brought back to the main /send page and the recipient info is now populated correctly with the recipient and provider you just selected

### PR DESCRIPTION
**Pull request by alekseevaiana**
Closes #8

### CODE REVIEW

**Comment by alekseevaiana** [comment]
@pi0neerpat I was working on the issue around 4 hours (had to learn new concepts). I was able to understand and implement a wizard, so it looks like it is going to work as expected. Then I implemented basic style, but there is some work ahead as well. The problem I had with form implementations and state changes, so stopped on learning about the FormProvider, I think that it can help, since this logic already in the project. So I will stop for now, as we agreed about 4 hours, but I ready to work ahead after your feedback on it.

**Comment by pi0neerpat** [comment]
I think you're on the right path here! Please continue

**Comment by alekseevaiana** [comment]
https://github.com/UseKeyp/kaching-app/assets/36742189/0f53838b-c548-4aa4-8baf-6c6c5c5a6e20

**Review by pi0neerpat — APPROVED** [review]
Nice work!

**Pull request merged**
